name: Latest Blog Posts Workflow

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    # ↓ これを追加して Node.js 24 を使うように伝えます
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in Zenn posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://zenn.dev/miki_mini/feed"
          max_post_count: 5
